
--
-- LibSQL SQL Schema dump automatic generated by geni
--

CREATE TABLE schema_migrations (id VARCHAR(255) NOT NULL PRIMARY KEY);
CREATE TABLE tags (slug TEXT PRIMARY KEY, name TEXT NOT NULL, kind_slug TEXT NOT NULL REFERENCES tag_kinds (slug) ON DELETE RESTRICT, system INTEGER NOT NULL DEFAULT 0);
CREATE INDEX idx_tags_name ON tags (name);
CREATE TABLE tag_kinds (slug TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE INDEX idx_tags_kind ON tags (kind_slug);
CREATE TABLE images (slug TEXT PRIMARY KEY, ext TEXT NOT NULL, name TEXT NOT NULL, added_at INTEGER NOT NULL, size_bytes INTEGER NOT NULL, width_px INTEGER NOT NULL, height_px INTEGER NOT NULL, sha256 TEXT NOT NULL, ready INTEGER NOT NULL);
CREATE TABLE image_tags (image_slug TEXT NOT NULL, tag_slug TEXT NOT NULL, PRIMARY KEY (image_slug, tag_slug), FOREIGN KEY (image_slug) REFERENCES images (slug) ON DELETE CASCADE, FOREIGN KEY (tag_slug) REFERENCES tags (slug) ON DELETE CASCADE);
CREATE INDEX idx_images_added_at ON images (added_at);